version: "3.5"

services:
  postgres:
    build: ./tori-back/postgres
    image: laurihakala/tori-postgres
    restart: always
    networks: 
      - defaultnetwork
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tori
    ports:
      - 5432:5432

  docker-backend:
    build: ./tori-back
    image: laurihakala/tori-backend
    networks: 
      - defaultnetwork
    environment:
      - PG_USER=username
      - PG_PASSWORD=password
      - PG_DATABASE=tori
      - PG_HOST=postgres
      - SECRET=TORISECRET
    ports:
      - 4000:4000


  docker-frontend:
    build: ./tori-front
    image: laurihakala/tori-frontend
    networks: 
      - defaultnetwork
    environment:
      - REACT_APP_API_URL=http://localhost:4000/api
    ports:
      - 80:80


networks: 
  defaultnetwork:

